# Generated by Django 6.0.5 on 2026-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tipo',
            field=models.CharField(choices=[('video', 'Video'), ('imagen', 'Imagen')], default='video', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='archivo',
            field=models.FileField(upload_to='multimedia/'),
        ),
    ]
