# Generated by Django 6.0.5 on 2026-06-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_video_tipo_alter_video_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categorias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
